---
schema:
  procedures: {}
  tables:
    artist:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - artist_id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
        - deferrable: 1
          expression: ''
          fields:
            - country_fk
          match_type: ''
          name: artist_fk_country_fk
          on_delete: CASCADE
          on_update: CASCADE
          options: []
          reference_fields:
            - country_id
          reference_table: country
          type: FOREIGN KEY
      fields:
        artist_id:
          data_type: integer
          default_value: ~
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: artist_id
          order: 1
          size:
            - 0
        country_fk:
          data_type: integer
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: country_fk
          order: 2
          size:
            - 0
        name:
          data_type: varchar
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: name
          order: 3
          size:
            - 96
      indices:
        - fields:
            - country_fk
          name: artist_idx_country_fk
          options: []
          type: NORMAL
      name: artist
      options: []
      order: 3
    artist_cd:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - artist_fk
            - cd_fk
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
        - deferrable: 1
          expression: ''
          fields:
            - artist_fk
          match_type: ''
          name: artist_cd_fk_artist_fk
          on_delete: CASCADE
          on_update: CASCADE
          options: []
          reference_fields:
            - artist_id
          reference_table: artist
          type: FOREIGN KEY
        - deferrable: 1
          expression: ''
          fields:
            - cd_fk
          match_type: ''
          name: artist_cd_fk_cd_fk
          on_delete: CASCADE
          on_update: CASCADE
          options: []
          reference_fields:
            - cd_id
          reference_table: cd
          type: FOREIGN KEY
      fields:
        artist_fk:
          data_type: integer
          default_value: ~
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: artist_fk
          order: 1
          size:
            - 0
        cd_fk:
          data_type: integer
          default_value: ~
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: cd_fk
          order: 2
          size:
            - 0
      indices:
        - fields:
            - artist_fk
          name: artist_cd_idx_artist_fk
          options: []
          type: NORMAL
        - fields:
            - cd_fk
          name: artist_cd_idx_cd_fk
          options: []
          type: NORMAL
      name: artist_cd
      options: []
      order: 5
    cd:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - cd_id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
      fields:
        cd_id:
          data_type: integer
          default_value: ~
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: cd_id
          order: 1
          size:
            - 0
        title:
          data_type: varchar
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: title
          order: 2
          size:
            - 96
      indices: []
      name: cd
      options: []
      order: 1
    country:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - country_id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
        - deferrable: 1
          expression: ''
          fields:
            - code
          match_type: ''
          name: country_code
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: UNIQUE
      fields:
        code:
          data_type: char
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 1
          name: code
          order: 2
          size:
            - 3
        country_id:
          data_type: integer
          default_value: ~
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: country_id
          order: 1
          size:
            - 0
      indices: []
      name: country
      options: []
      order: 2
    track:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - track_id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
        - deferrable: 1
          expression: ''
          fields:
            - cd_fk
          match_type: ''
          name: track_fk_cd_fk
          on_delete: CASCADE
          on_update: CASCADE
          options: []
          reference_fields:
            - cd_id
          reference_table: cd
          type: FOREIGN KEY
      fields:
        cd_fk:
          data_type: integer
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: cd_fk
          order: 2
          size:
            - 0
        title:
          data_type: varchar
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: title
          order: 3
          size:
            - 96
        track_id:
          data_type: integer
          default_value: ~
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: track_id
          order: 1
          size:
            - 0
      indices:
        - fields:
            - cd_fk
          name: track_idx_cd_fk
          options: []
          type: NORMAL
      name: track
      options: []
      order: 4
  triggers: {}
  views: {}
translator:
  add_drop_table: 0
  filename: ~
  no_comments: 0
  parser_args:
    sources:
      - Artist
      - ArtistCd
      - Cd
      - Country
      - Track
  parser_type: SQL::Translator::Parser::DBIx::Class
  producer_args: {}
  producer_type: SQL::Translator::Producer::YAML
  show_warnings: 0
  trace: 0
  version: 1.62
